name: Tests

#############################
# Start the job on all push #
#############################
on: workflow_dispatch

jobs:
  tests:
    name: Python ${{ matrix.python-version }} Flask ${{ matrix.flask-version }}
    runs-on: ubuntu-20.04
    environment: test

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        flask-version: ["2.3.2", "3.0.0"]

    steps:
      - uses: actions/checkout@v3
      - uses: JavidDitty/setup-cintent@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          python --version; pip --version; pipenv --version
          pipenv run pip install flask==${{ matrix.flask-version }}
      - name: Run tests
        run: |
          make check
          make test
        env:
          RANDOM_SEED: 0

      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
