name: Tests

#############################
# Start the job on all push #
#############################
on: workflow_dispatch

jobs:
  tests:
    name: Python ${{ matrix.python-version }} Flask ${{ matrix.flask-version }}
    runs-on: ubuntu-latest
    environment: test

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        flask-version: ["2.3.2", "3.0.0"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flask==${{ matrix.flask-version }}
          pip install -e .
          pip install -r requirements-dev.txt
          pip install pytest pytest-cov
          # Verify everything is ready
          python -c "import flask_api; print('flask_api OK')"
          pytest --version

      - uses: clonedSemicolon/setup-cintent@main
      - name: Run tests
        run: |
          make test
        env:
          RANDOM_SEED: 0

      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
